import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.sass";

import Main from "../components/pages/main/Main";
import { useState } from "react";

import { useHttp } from "../hooks/http.hook";

// export const getServerSideProps = async () => {
//     const options = {
//         method: "GET",
//         headers: {
//             "X-RapidAPI-Key": "660acd6f64msh16b15f2e86fab3ep160cf2jsn20fce72e0ccb",
//             "X-RapidAPI-Host": "free-to-play-games-database.p.rapidapi.com",
//         },
//     };

//     const res = await fetch("https://free-to-play-games-database.p.rapidapi.com/api/games?platform=pc", options);
//     const data = await res.json();

//     return {
//         props: { games: data },
//     };
// };

export const getServerSideProps = async () => {
    const { request } = useHttp();

    let err = false;
    const options = {
        "X-RapidAPI-Key": "660acd6f64msh16b15f2e86fab3ep160cf2jsn20fce72e0ccb",
        "X-RapidAPI-Host": "free-to-play-games-database.p.rapidapi.com",
    };

    const res = await request(
        "https://free-to-play-games-database.p.rapidapi.com/api/games?platform=pc",
        "GET",
        null,
        options
    ).catch(e => (err = true));

    return {
        props: { games: res, error: err },
    };
};

export default function Home({ games, error }: any) {
    return (
        <>
            <Head>
                <title>Games</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                <Main prerenderedGames={games} prerenderError={error} />
            </main>
        </>
    );
}
